apiVersion: v1
kind: Service
metadata:
  name: working-sample-service
  labels:
    application: core-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    application: core-app
    name: deployment1
