namespace: namespace1
commonLabels:
  env: namespace1
resources:
  - ../../base
  - autoscaling.yaml
configMapGenerator:
  - name: sample-config-map
    behavior: merge
    envs:
      - namespace1.env
patchesStrategicMerge:
  - patch-deployment.yaml

images:
  - name: application-image:tag-version
    newName: 123456789100.dkr.ecr.ap-northeast-1.amazonaws.com/namespace1/java
    newTag: v1.0.0

secretGenerator:
  - envs:
      - secrets/deployment1-secrets
    name: sample-secrets
    type: Opaque
