apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  template:
    spec:
      containers:
        - name: app0
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "50m"
              memory: "150Mi"
