name: 'Kustomize GitHub Actions'
run-name: Verifying the Commit pushed by ${{ github.actor }}
on: [push]
jobs:
  kustomize:
    name: 'Kustomize'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Kustomize Build'
        uses: amit-naudiyal/kubernetes-kustomize-framework@main
        with:
          kustomize_version: '3.0.0'
          kustomize_build_dir: 'working-samples/overlays/staging'
          kustomize_comment: true
          kustomize_output_file: "gitops/rendered.yaml"
          kustomize_build_options: "--load_restrictor none"
          enable_alpha_plugins: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}